// <auto-generated />
using System;
using IrentaFormTestBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IrentaFormTestBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230405210541_ownership")]
    partial class ownership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("IrentaFormTestBackend.Models.OwnershipBankDetails", b =>
                {
                    b.Property<ulong>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BankBranchName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Bic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheckingAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrespondentAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("OwnershipFormModelKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasIndex("OwnershipFormModelKey");

                    b.ToTable("OwnershipBankDetailsEnumerable");
                });

            modelBuilder.Entity("IrentaFormTestBackend.Models.OwnershipFormModel", b =>
                {
                    b.Property<ulong>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("Inn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NoAgreement")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Ogrnip")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanEgrip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanInn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanLeaseAgreement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanOgrnip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("OwnershipFormModels");
                });

            modelBuilder.Entity("IrentaFormTestBackend.Models.OwnershipBankDetails", b =>
                {
                    b.HasOne("IrentaFormTestBackend.Models.OwnershipFormModel", "OwnershipFormModel")
                        .WithMany("OwnershipBankDetailsList")
                        .HasForeignKey("OwnershipFormModelKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnershipFormModel");
                });

            modelBuilder.Entity("IrentaFormTestBackend.Models.OwnershipFormModel", b =>
                {
                    b.Navigation("OwnershipBankDetailsList");
                });
#pragma warning restore 612, 618
        }
    }
}
